language: python
branches:
  only:
  - master
env:
  global:
  - PACKER_VERSION="1.2.2"
notifications:
  email: false
  slack:
    rooms:
      secure: ZmbnJhM4qTzjiNAforDwMHg6jRe8DiiJzU+Db5vRMw1ymp+doz+nFruBEsZFUUlc+23YtfyklsjDVqRZsSMAtWjk/fkjeoJA3nMPMhJJ2IBwepaQhx0utmrAajqcb2qymFn9uKkn332Oibr54KWYn7qNf1Yijhv7PW091AMvA+/D6Y3cYkHSKTD5sFzGPYEm2TwNlV6vZtsDDY5zA/HGhw/x2tu7vsZcthvLMWz923xk7Dcgf0mVL28I081nfuN5JJUSWZBLQchhnFGjBNIJI7jutEMq3swNV8oWC2QyKgEI8tb529rcDKXd+tzAjoBENKvHEqjaf3XySe57P4JeAgOWz71HBrww0pmCthAnyr8MEukcEgKfo+hPkbP2lFn6xXqJ27AUgI8WdIGNHXsesfdfRReGm41qZ/oRe2JmVfz/D1Mt7ZyWgC9ksW4SGZknjBsVbQIObmyARXx9pHOLTyPZyY2x6Fch9Gz+9xCxFZWxR3ef27QTyyY4B8/YHDQmv1knH4R9H8jHfNM41ys21vmjLCBQpWIP0abn5Q+DrUyMbuUwejevmLkFcYo/Xyq1N1F2VKei3FRTEAV8laJBG8rfDXW+XydIzm0hskJCJs1Gq1lDAXOXbG7bLZUk3BWPiqtNaiyfeNyWJqa/u/DlfY+8T4NbfC+7nkfWD0cO8+c=
before_install:
- sudo apt-get update -y --fix-missing
install:
- packer --version
- curl -o /tmp/packer.zip -L "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
- sudo unzip -d /usr/local/packer-${PACKER_VERSION} /tmp/packer.zip
- sudo ln -sf /usr/local/packer-${PACKER_VERSION}/packer /usr/local/bin/packer
- packer --version
- sudo apt-get install -y jq
- pip install awscli --upgrade
- aws --version
script:
- "./build.sh"
after_success:
- "./send-datadog-event.sh vault"
